version: '3'
services: 
  app:
      build: .
      ports: 
          - 8000:8000
      restart: always
      depends_on:
        - db
  db:
      image: mysql:8.0.27
      volumes:
        - ./database/migration:/docker-entrypoint-initdb.d
        - dbdata:/var/lib/mysql/
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
      ports:
        - 3306:3306
  prometheus:
    image: prom/prometheus:v2.27.1
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana-provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=grafana
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes: 
  dbdata:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local