// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repositories/interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/scys12/cake-store/internal/types"
)

// MockICakeRepo is a mock of ICakeRepo interface.
type MockICakeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockICakeRepoMockRecorder
}

// MockICakeRepoMockRecorder is the mock recorder for MockICakeRepo.
type MockICakeRepoMockRecorder struct {
	mock *MockICakeRepo
}

// NewMockICakeRepo creates a new mock instance.
func NewMockICakeRepo(ctrl *gomock.Controller) *MockICakeRepo {
	mock := &MockICakeRepo{ctrl: ctrl}
	mock.recorder = &MockICakeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICakeRepo) EXPECT() *MockICakeRepoMockRecorder {
	return m.recorder
}

// DeleteCake mocks base method.
func (m *MockICakeRepo) DeleteCake(arg0 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCake", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCake indicates an expected call of DeleteCake.
func (mr *MockICakeRepoMockRecorder) DeleteCake(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCake", reflect.TypeOf((*MockICakeRepo)(nil).DeleteCake), arg0)
}

// InsertCake mocks base method.
func (m *MockICakeRepo) InsertCake(arg0 *types.Cake) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCake", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertCake indicates an expected call of InsertCake.
func (mr *MockICakeRepoMockRecorder) InsertCake(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCake", reflect.TypeOf((*MockICakeRepo)(nil).InsertCake), arg0)
}

// UpdateCake mocks base method.
func (m *MockICakeRepo) UpdateCake(arg0 *types.Cake) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCake", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCake indicates an expected call of UpdateCake.
func (mr *MockICakeRepoMockRecorder) UpdateCake(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCake", reflect.TypeOf((*MockICakeRepo)(nil).UpdateCake), arg0)
}
