CREATE TABLE cake
(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR
(255),
  description VARCHAR
(255),
  rating INT,
  image VARCHAR
(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);