// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/scys12/cake-store/internal/types"
)

// MockICakeService is a mock of ICakeService interface.
type MockICakeService struct {
	ctrl     *gomock.Controller
	recorder *MockICakeServiceMockRecorder
}

// MockICakeServiceMockRecorder is the mock recorder for MockICakeService.
type MockICakeServiceMockRecorder struct {
	mock *MockICakeService
}

// NewMockICakeService creates a new mock instance.
func NewMockICakeService(ctrl *gomock.Controller) *MockICakeService {
	mock := &MockICakeService{ctrl: ctrl}
	mock.recorder = &MockICakeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICakeService) EXPECT() *MockICakeServiceMockRecorder {
	return m.recorder
}

// DeleteCake mocks base method.
func (m *MockICakeService) DeleteCake(arg0 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCake", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCake indicates an expected call of DeleteCake.
func (mr *MockICakeServiceMockRecorder) DeleteCake(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCake", reflect.TypeOf((*MockICakeService)(nil).DeleteCake), arg0)
}

// GetCakeDetail mocks base method.
func (m *MockICakeService) GetCakeDetail(arg0 int64) (*types.CakeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCakeDetail", arg0)
	ret0, _ := ret[0].(*types.CakeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCakeDetail indicates an expected call of GetCakeDetail.
func (mr *MockICakeServiceMockRecorder) GetCakeDetail(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCakeDetail", reflect.TypeOf((*MockICakeService)(nil).GetCakeDetail), arg0)
}

// GetListOfCake mocks base method.
func (m *MockICakeService) GetListOfCake(arg0 string, arg1 int64) (*types.CakesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListOfCake", arg0, arg1)
	ret0, _ := ret[0].(*types.CakesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListOfCake indicates an expected call of GetListOfCake.
func (mr *MockICakeServiceMockRecorder) GetListOfCake(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListOfCake", reflect.TypeOf((*MockICakeService)(nil).GetListOfCake), arg0, arg1)
}

// InsertCake mocks base method.
func (m *MockICakeService) InsertCake(arg0 types.CakeRequest) (*types.CakeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCake", arg0)
	ret0, _ := ret[0].(*types.CakeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertCake indicates an expected call of InsertCake.
func (mr *MockICakeServiceMockRecorder) InsertCake(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCake", reflect.TypeOf((*MockICakeService)(nil).InsertCake), arg0)
}

// UpdateCake mocks base method.
func (m *MockICakeService) UpdateCake(arg0 int64, arg1 types.CakeRequest) (*types.CakeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCake", arg0, arg1)
	ret0, _ := ret[0].(*types.CakeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCake indicates an expected call of UpdateCake.
func (mr *MockICakeServiceMockRecorder) UpdateCake(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCake", reflect.TypeOf((*MockICakeService)(nil).UpdateCake), arg0, arg1)
}
